FROM python:3.9-slim-buster

RUN apt-get update

WORKDIR /opt/app

COPY ./sentence-rewriting/requirements.txt .
RUN pip install -r requirements.txt

# Copy the app files
COPY ./sentence-rewriting .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
