version: '3'

services:
  next_word_prob:
    build:
      context: .
      dockerfile: Dockerfile.next-word
    ports:
      - 8000:8000
  
  sentence_rewriting:
    build:
      context: .
      dockerfile: Dockerfile.sentence-rewriting
    ports:
      - 8001:8001