FROM python:3.9-slim-buster

RUN apt-get update

WORKDIR /opt/app

COPY ./ui-service/requirements.txt .
RUN pip install -r requirements.txt

# Copy the app files
COPY ./ui-service .

CMD ["streamlit", "run", "Home.py", "--server.port", "8080"]
