version: '3'

services:
  api_service:
    build:
      context: .
      dockerfile: Dockerfile.api-service
    restart: always
    ports:
      - "8000:8000"
  
  api_service:
    build:
      context: .
      dockerfile: Dockerfile.ui-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - API_SERVICE_URL=http://api_service:8000