FROM python:3.9-slim-buster

RUN apt-get update

WORKDIR /opt/app

COPY ./next-word-probability/requirements.txt .
RUN pip install -r requirements.txt

# Copy the app files
COPY ./next-word-probability .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
