FROM python:3.9-slim-buster

RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/app

COPY ./api-service/requirements.txt .
RUN pip install -r requirements.txt

# Copy the app files
COPY ./api-service .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "info"]