POS_MAPS = {
    "CC": "CC Coordinating conjunction: for, and, nor, but, or, yet, so",
    "CD": "CD Cardinal number: one, two, twenty-four",
    "DT": "DT Determiner: a, an, all, many, much, any, some, this",
    "EX": "EX Existential there: there (no other words)",
    "FW": "FW Foreign word: infinitum, ipso",
    "IN": "IN Preposition/subordinate conjunction: except, inside, across, on, through, beyond, with, without",
    "JJ": "JJ Adjective: beautiful, large, inspectable",
    "JJR": "JJR Adjective, comparative: larger, quicker",
    "JJS": "JJS Adjective, superlative: largest, quickest",
    "JJ.*": "JJ.*: Matches any adjective in the list of JJ, JJR, and JJS. Can be an adjective, comparative adjective, or superlative adjective",
    "LS": "LS List item marker: not used by LanguageTool",
    "MD": "MD Modal: should, can, need, must, will, would",
    "NN": "NN Noun, singular count noun: bicycle, earthquake, zipper",
    "NNS": "NNS Noun, plural: bicycles, earthquakes, zippers",
    "NN:U": "NN:U Nouns that are always uncountable #new tag - deviation from Penn, examples: admiration, Afrikaans",
    "NN:UN": "NN:UN Nouns that might be used in the plural form and with an indefinite article, depending on their meaning #new tag - deviation from Penn, examples: establishment, wax, afternoon",
    "NNP": "NNP Proper noun, singular: Denver, DORAN, Alexandra",
    "NNPS": "NNPS Proper noun, plural: Buddhists, Englishmen",
    "ORD": "ORD Ordinal number: first, second, twenty-third, hundredth #New tag (experimental) since LT 4.9. Specified in disambiguation.xml. Examples: first, second, third, twenty-fourth, seventy-sixth",
    "PCT": "PCT Punctuation mark: (`.,;:…!?`) #new tag - deviation from Penn",
    "PDT": "PDT Predeterminer: all, sure, such, this, many, half, both, quite",
    "POS": "POS Possessive ending: s (as in: Peter's)",
    "PRP": "PRP Personal pronoun: everyone, I, he, it, myself",
    "PRP$": "PRP$ Possessive pronoun: its, our, their, mine, my, her, his, your",
    "RB": "RB Adverb and negation: easily, sunnily, suddenly, specifically, not",
    "RBR": "RBR Adverb, comparative: better, faster, quicker",
    "RBS": "RBS Adverb, superlative: best, fastest, quickest",
    "RB_SENT": "RB_SENT Adverbial phrase including a comma that starts a sentence. #New tag (experimental) since LT 4.8. Specified in disambiguation.xml. Examples: However, Whenever possible, First of all, On the other hand,",
    "RP": "RP Particle: in, into, at, off, over, by, for, under",
    "SENT_END": "SENT_END: LanguageTool tags the last token of a sentence as both SENT_END and a regular part-of-speech tag.",
    "SENT_START": "SENT_START: LanguageTool tags the first token of a sentence as both SENT_START and a regular part-of-speech tag.",
    "SYM": "SYM Symbol: rarely used by LanguageTool (e.g. for 'DD/MM/YYYY')",
    "TO": "TO to: to (no other words)",
    "UH": "UH Interjection: aargh, ahem, attention, congrats, help",
    "VB": "VB Verb, base form: eat, jump, believe, be, have",
    "VBD": "VBD Verb, past tense: ate, jumped, believed",
    "VBG": "VBG Verb, gerund/present participle: eating, jumping, believing",
    "VBN": "VBN Verb, past participle: eaten, jumped, believed",
    "VBP": "VBP Verb, non-3rd ps. sing. present: eat, jump, believe, am (as in 'I am'), are",
    "VBZ": "VBZ Verb, 3rd ps. sing. present: eats, jumps, believes, is, has",
    "WDT": "WDT wh-determiner: that, whatever, what, whichever, which (no other words)",
    "WP": "WP wh-pronoun: that, whatever, what, whatsoever, whomsoever, whosoever, who, whom, whoever, whomever, which (no other words)",
    "WP$": "WP$ Possessive wh-pronoun: whose (no other words)",
    "WRB": "WRB wh-adverb: however, how, wherever, where, when, why",
}
